#!/bin/bash
sudo yum install -y mysql-devel
sudo yum install gcc
sudo yum install git
sudo yum install python3-devel
pip install -r /home/ec2-user/sample-app/requirements.txt
git clone https://github.com/patilps249/Skillolympics_Trial.git
